os:
  - linux

sudo: required

services:
  - docker

language: go

go:
  - "tip"
  - "1.16"

script:
  - make check

notifications:
  email:
    - tiago.katcipis@neoway.com.br
    - matheus.vill@neoway.com.br
    - kamila.hinckel@neoway.com.br
    - leonardo.borges@neoway.com.br
    - josue.machado@neoway.com.br
    - murilo.medeiros@neoway.com.br
    - victor.vieira@neoway.com.br